# Generated by Django 3.1.3 on 2020-12-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20201226_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('Educated', 'Educated'), ('Regular', 'Regular'), ('Under Educated', 'Under Educated')], max_length=24, null=True),
        ),
    ]
