# Generated by Django 3.1.3 on 2020-12-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201228_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_preference',
            field=models.CharField(blank=True, choices=[('Educated', 'Educated'), ('Regular', 'Regular'), ('Under Educated', 'Under Educated')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intelligence_preference',
            field=models.CharField(blank=True, choices=[('Intellectual', 'Intellectual'), ('Regular', 'Regular'), ('Not at All', 'Not at All')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personality_type_preference',
            field=models.CharField(blank=True, choices=[('Type A', 'Type A'), ('Type B', 'Type B')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='temperament_preference',
            field=models.CharField(blank=True, choices=[('Boring', 'Boring'), ('Quiet', 'Quiet'), ('Loud', 'Loud')], max_length=24, null=True),
        ),
    ]
