# Generated by Django 3.1.3 on 2020-12-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_userreadytoplaygames'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserReadyToPlayGames',
        ),
    ]
