# Generated by Django 3.1.3 on 2021-01-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210105_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='online',
        ),
        migrations.AddField(
            model_name='profile',
            name='online_count',
            field=models.IntegerField(default=0),
        ),
    ]
