# Generated by Django 3.1.3 on 2021-01-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210118_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='online_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
