# Generated by Django 3.1.3 on 2021-01-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20210118_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='online',
        ),
        migrations.AddField(
            model_name='profile',
            name='online_count',
            field=models.IntegerField(default=0),
        ),
    ]
